test: &default

  # Credentials for REST APIs
  mode: sandbox
  client_id: <%= Rails.application.credentials.config.dig(:paypal, :client_id) %>
  client_secret: <%= Rails.application.credentials.config.dig(:paypal, :client_secret) %>
  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
  client_id: <%= Rails.application.credentials.config.dig(:paypal, :client_id) %>
  client_secret: <%= Rails.application.credentials.config.dig(:paypal, :client_secret) %>
  ssl_options:
    ca_file: null
